export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const PUB_SUB = 'PUB_SUB';
export const NEW_PENDING_ORDER = 'NEW_PENDING_ORDER';
export const NEW_ACCEPTED_ORDER = 'NEW_ACCEPTED_ORDER';
export const NEW_COOKED_ORDER = 'NEW_COOKED_ORDER';
export const GET_ORDER_STATE = 'GET_ORDER_STATE';
